/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import Funciones.BasededatosManager;
import Funciones.FileChuser;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MauricioNTHINGs
 */
public class ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ventas
     */
    String directorio, user,pass;
    FileChuser dir=new FileChuser();
    BasededatosManager bd=new BasededatosManager();
    public ventas(String usuario, String contra) {
        this.user=usuario;
        this.pass=contra;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateChooser = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        meschooser = new com.toedter.calendar.JMonthChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Reporte Ventas");

        jButton1.setText("TODAS LAS FECHAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("FECHA ESPECÍFICA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(meschooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(meschooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DateChooser.setDateFormatString("dd/MM/yyyy");
        SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        String fecha=format.format(DateChooser.getDate());
        generarReporte("SELECT COUNT(*) FROM Ventas V, Empleado E, Pedido P, Cajeros C WHERE V.cajeros_id_cajero=C.id_cajero AND C.empleado_id_empleado=E.id_empleado AND V.pedido_numpedido=P.numpedido AND V.fecha='"+fecha+"';","SELECT V.id_venta, E.nombre, P.totalneto, V.fecha FROM Ventas V, Empleado E, Pedido P, Cajeros C WHERE V.cajeros_id_cajero=C.id_cajero AND C.empleado_id_empleado=E.id_empleado AND V.pedido_numpedido=P.numpedido AND V.fecha='"+fecha+"' ORDER BY `V`.`id_venta` ASC;");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generarReporte("SELECT COUNT(*) FROM Ventas V, Empleado E, Pedido P, Cajeros C WHERE V.cajeros_id_cajero=C.id_cajero AND C.empleado_id_empleado=E.id_empleado AND V.pedido_numpedido=P.numpedido;","SELECT V.id_venta, E.nombre, P.totalneto, V.fecha FROM Ventas V, Empleado E, Pedido P, Cajeros C WHERE V.cajeros_id_cajero=C.id_cajero AND C.empleado_id_empleado=E.id_empleado AND V.pedido_numpedido=P.numpedido ORDER BY `V`.`id_venta` ASC;");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int mes=meschooser.getMonth()+1;
        generarReporte("SELECT COUNT(*) FROM Ventas V, Empleado E, Pedido P, Cajeros C WHERE V.cajeros_id_cajero=C.id_cajero AND C.empleado_id_empleado=E.id_empleado AND V.pedido_numpedido=P.numpedido AND EXTRACT(month FROM V.fecha)='"+mes+"';","SELECT V.id_venta, E.nombre, P.totalneto, V.fecha FROM Ventas V, Empleado E, Pedido P, Cajeros C WHERE V.cajeros_id_cajero=C.id_cajero AND C.empleado_id_empleado=E.id_empleado AND V.pedido_numpedido=P.numpedido AND EXTRACT(month FROM V.fecha)='"+mes+"' ORDER BY `V`.`id_venta` ASC;");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    void generarReporte(String sql1, String sql2){
        try {
            // TODO add your handling code here:
            this.directorio=dir.obtenerDirectorio(".pdf");
            File archivo=new File(directorio);
            Document documento=new Document(PageSize.A4.rotate());
            FileOutputStream ficheroPdf=new FileOutputStream(archivo);
            PdfWriter.getInstance(documento, ficheroPdf).setInitialLeading(20);
            documento.setMargins(0,0,1,0);
            documento.open();
            
            PdfPTable tablaheader=new PdfPTable(1);
            Font c=new Font(Font.FontFamily.HELVETICA,22,Font.BOLD,BaseColor.BLACK);
            PdfPCell celda1=new PdfPCell(new Paragraph("Reporte De Ventas",c));
            celda1.setBackgroundColor(BaseColor.BLUE);
            tablaheader.addCell(celda1);
            ResultSet consultanombreempresa=bd.consultar("SELECT nombreempresa FROM configuracion;", user, pass);
            if(consultanombreempresa.next()){
                PdfPCell celda2=new PdfPCell(new Paragraph(consultanombreempresa.getString("nombreempresa").toUpperCase(),c));
                tablaheader.addCell(celda2);
            }
            documento.add(tablaheader);
            
            PdfPTable tablareporte=new PdfPTable(4);
            PdfPCell celdaid=new PdfPCell(new Paragraph("ID"));
            tablareporte.addCell(celdaid);
            PdfPCell celdacajero=new PdfPCell(new Paragraph("Nombre Cajero"));
            tablareporte.addCell(celdacajero);
            PdfPCell celdatotalventa=new PdfPCell(new Paragraph("Total Venta"));
            tablareporte.addCell(celdatotalventa);
            PdfPCell celdafecha=new PdfPCell(new Paragraph("Fecha Venta"));
            tablareporte.addCell(celdafecha);
            int filas=0;
            ResultSet contarfilas=bd.consultar(sql1, user, pass);
            while(contarfilas.next()){
                filas=contarfilas.getInt(1);
            }
            ResultSet reporteconsulta=bd.consultar(sql2, user, pass);
            while (reporteconsulta.next()) {
                PdfPCell celdaa = new PdfPCell(new Paragraph(reporteconsulta.getString("id_venta")));
                tablareporte.addCell(celdaa);
                PdfPCell celdab = new PdfPCell(new Paragraph(reporteconsulta.getString("nombre")));
                tablareporte.addCell(celdab);
                PdfPCell celdac = new PdfPCell(new Paragraph(reporteconsulta.getString("totalneto")));
                tablareporte.addCell(celdac);
                PdfPCell celdad = new PdfPCell(new Paragraph(reporteconsulta.getString("fecha")));
                tablareporte.addCell(celdad);
            }
            documento.add(tablareporte);
            documento.close();
            ejecutarPDF();
        } catch (DocumentException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ejecutarPDF(){
        String d = "";
        try {

            if ("/".equals(directorio.substring(0, 1))) {
                Runtime.getRuntime().exec("evince " + directorio);
            }
            if (":".equals(directorio.substring(1, 2))) {
                char signo = (char) 92;
                String[] arreglo = directorio.split("\\\\");
                for (int a = 0; a < arreglo.length; a++) {
                    d = d + arreglo[a] + "\\\\\\\\";
                }
                Desktop.getDesktop().open(new File(d));
            }
        } catch (IOException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JMonthChooser meschooser;
    // End of variables declaration//GEN-END:variables
}
